SUPABASE_URL = "https://fyyvubvceijyeuhvncri.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable__R5PSqn3VUYXJdcy-RsXOQ_69pJelxj"
SUPABASE_SERVICE_ROLE_KEY = "sb_secret_6_rjTvd7gJTFK4dvJ8EatA_YHl4vX7y"
SUPABASE_TABLE = "Contagens"

ENTRY_USERNAME = "ibe"
ENTRY_PASSWORD = "ibe"
